# .github/workflows/run_crew.yml (FINAL, FOOLPROOF VERSION)

name: 'Run AI Crew'

on:
  issues:
    types: [opened]

jobs:
  run-crew-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run The AI Crew
        env:
          # Yahan hum secrets ko bilkul sahi naam se call kar rahe hain
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python main.py
