# .github/workflows/run_crew.yml (The AI Factory Supervisor)

name: 'Run AI Crew'

on:
  issues:
    types: [opened]

jobs:
  run-crew-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run The AI Crew
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENROUTER_API_KEY }} # Yahan hum OpenRouter ki key daal rahe hain
          OPENAI_API_BASE: "https://openrouter.ai/api/v1" # CrewAI ko batayein ke OpenAI nahi, OpenRouter se baat karni hai
          OPENAI_MODEL_NAME: "mistralai/mistral-7b-instruct:free" # 100% Free model
        run: python main.py
